name: "Pull Request Tests"

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.9

    services:
      redis:
        image: redis:6.2-alpine
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      
      - name: Install dependencies
        working-directory: ./Commander
        run: python -m pip install -r requirements.txt

      - name: Run tests
        working-directory: ./Commander
        run: pytest --cov --cov-report=xml
        env:
          REDIS_URI: redis://redis:6379

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./Commander/coverage.xml